package system.dashboard;

public enum ConversationStateAttack {
        CASE1, CASE2, CASE3, CASE4, MISTAKE1, CASE5, CASE6, CASE7, CASE8, CASE9, CASE10,
        CASE11, CASE12, CASE13, CASE14, CASE15, CASE16,
        CASESUB1, CASESUB2, CASESUB3, CASESUB4, CASESUB5, CASESUB6, CASESUB7, CASESUB8, 
        DEATH, CASE21,LOSER,STOPPER;
    }